<section class="faq">
    <div class="faq__container main-container">
        <h2 class="faq__title">
            частые вопросы
        </h2>
        <div class="faq__list">
            <div class="faq__item faq__item-active">
                <div class="faq__item-header">
                    <h3 class="faq__item-title">Как оплатить тарифный план</h3>
                    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <line class="vertical" y1="10" x2="20" y2="10" stroke="white" stroke-width="2"/>
                        <line class="horizontal" x1="10" y1="20" x2="10" y2="4.37114e-08" stroke="white" stroke-width="2"/>
                    </svg>
                </div>
                <div class="faq__item-content" style="display: none;">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fugit impedit quasi sapiente vero? Cupiditate dolorum error esse minima quod sapiente similique veritatis vitae! Doloremque, quidem veniam? Eum, laborum, maiores.</span><span>Alias aliquid doloribus ducimus eligendi, eos fugiat labore libero obcaecati officiis quod reiciendis repellat! Accusantium doloribus ducimus inventore ipsam nobis odit, omnis pariatur quia ratione, reprehenderit sed similique sunt, veniam.</span><span>Ab alias consequatur dolor dolore enim, eveniet fuga laudantium maxime nemo neque porro quaerat quam qui quidem repellendus sed tempore, ut vitae. Ducimus explicabo itaque iusto labore provident repellendus repudiandae!</span><span>A architecto aspernatur, assumenda atque consectetur, corporis deleniti dolorum eum illum inventore iure magnam mollitia, quas quasi quia saepe voluptatem? Aperiam distinctio iusto, laborum mollitia nobis perspiciatis quod sint vitae.</span><span>Alias animi blanditiis dolor doloremque ducimus eius fugit, libero magni mollitia necessitatibus nihil nostrum officiis perspiciatis placeat, repellat sit sunt suscipit! Eius impedit iure laborum nesciunt perspiciatis quibusdam quo suscipit.</span><span>A, aut, consectetur culpa cum delectus, dolore dolores doloribus enim facere pariatur quam quasi quibusdam vero. Animi distinctio doloremque ipsa maxime nisi numquam odio officiis, omnis reiciendis repellendus sed soluta!</span><span>Ad commodi consectetur dicta doloribus dolorum eius error esse et eveniet, exercitationem iste obcaecati similique sunt. Autem, culpa cupiditate deserunt, et ipsam molestias nam necessitatibus nostrum, optio quos tempore unde.</span><span>Ad assumenda atque commodi dicta dolor dolorem dolores, ducimus eligendi eum exercitationem, facilis fuga impedit incidunt ipsum laboriosam maxime molestiae necessitatibus nostrum quasi repellat repellendus sunt unde ut voluptates voluptatum!</span><span>Accusamus exercitationem iusto officia repellendus sed? Corporis eligendi fugiat iste nemo pariatur placeat quisquam quod repellat unde vel! Aperiam beatae debitis, distinctio laboriosam laborum natus ullam? Ducimus ipsum molestiae quia!</span><span>Ad blanditiis consequatur debitis eius in incidunt ipsum molestiae similique voluptas. Animi corporis iusto unde. A animi, delectus enim laboriosam libero magni quaerat quasi voluptas? Consequatur explicabo ipsam iste qui!</p>
                </div>
            </div>
            <div class="faq__item">
                <div class="faq__item-header">
                    <h3 class="faq__item-title">Как оплатить тарифный план</h3>
                    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <line class="vertical" y1="10" x2="20" y2="10" stroke="white" stroke-width="2"/>
                        <line class="horizontal" x1="10" y1="20" x2="10" y2="4.37114e-08" stroke="white" stroke-width="2"/>
                    </svg>
                </div>
                <div class="faq__item-content" style="display: none;">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fugit impedit quasi sapiente vero? Cupiditate dolorum error esse minima quod sapiente similique veritatis vitae! Doloremque, quidem veniam? Eum, laborum, maiores.</span><span>Alias aliquid doloribus ducimus eligendi, eos fugiat labore libero obcaecati officiis quod reiciendis repellat! Accusantium doloribus ducimus inventore ipsam nobis odit, omnis pariatur quia ratione, reprehenderit sed similique sunt, veniam.</span><span>Ab alias consequatur dolor dolore enim, eveniet fuga laudantium maxime nemo neque porro quaerat quam qui quidem repellendus sed tempore, ut vitae. Ducimus explicabo itaque iusto labore provident repellendus repudiandae!</span><span>A architecto aspernatur, assumenda atque consectetur, corporis deleniti dolorum eum illum inventore iure magnam mollitia, quas quasi quia saepe voluptatem? Aperiam distinctio iusto, laborum mollitia nobis perspiciatis quod sint vitae.</span><span>Alias animi blanditiis dolor doloremque ducimus eius fugit, libero magni mollitia necessitatibus nihil nostrum officiis perspiciatis placeat, repellat sit sunt suscipit! Eius impedit iure laborum nesciunt perspiciatis quibusdam quo suscipit.</span><span>A, aut, consectetur culpa cum delectus, dolore dolores doloribus enim facere pariatur quam quasi quibusdam vero. Animi distinctio doloremque ipsa maxime nisi numquam odio officiis, omnis reiciendis repellendus sed soluta!</span><span>Ad commodi consectetur dicta doloribus dolorum eius error esse et eveniet, exercitationem iste obcaecati similique sunt. Autem, culpa cupiditate deserunt, et ipsam molestias nam necessitatibus nostrum, optio quos tempore unde.</span><span>Ad assumenda atque commodi dicta dolor dolorem dolores, ducimus eligendi eum exercitationem, facilis fuga impedit incidunt ipsum laboriosam maxime molestiae necessitatibus nostrum quasi repellat repellendus sunt unde ut voluptates voluptatum!</span><span>Accusamus exercitationem iusto officia repellendus sed? Corporis eligendi fugiat iste nemo pariatur placeat quisquam quod repellat unde vel! Aperiam beatae debitis, distinctio laboriosam laborum natus ullam? Ducimus ipsum molestiae quia!</span><span>Ad blanditiis consequatur debitis eius in incidunt ipsum molestiae similique voluptas. Animi corporis iusto unde. A animi, delectus enim laboriosam libero magni quaerat quasi voluptas? Consequatur explicabo ipsam iste qui!</p>
                </div>
            </div>
            <div class="faq__item">
                <div class="faq__item-header">
                    <h3 class="faq__item-title">Как оплатить тарифный план</h3>
                    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <line class="vertical" y1="10" x2="20" y2="10" stroke="white" stroke-width="2"/>
                        <line class="horizontal" x1="10" y1="20" x2="10" y2="4.37114e-08" stroke="white" stroke-width="2"/>
                    </svg>
                </div>
                <div class="faq__item-content" style="display: none;">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fugit impedit quasi sapiente vero? Cupiditate dolorum error esse minima quod sapiente similique veritatis vitae! Doloremque, quidem veniam? Eum, laborum, maiores.</span><span>Alias aliquid doloribus ducimus eligendi, eos fugiat labore libero obcaecati officiis quod reiciendis repellat! Accusantium doloribus ducimus inventore ipsam nobis odit, omnis pariatur quia ratione, reprehenderit sed similique sunt, veniam.</span><span>Ab alias consequatur dolor dolore enim, eveniet fuga laudantium maxime nemo neque porro quaerat quam qui quidem repellendus sed tempore, ut vitae. Ducimus explicabo itaque iusto labore provident repellendus repudiandae!</span><span>A architecto aspernatur, assumenda atque consectetur, corporis deleniti dolorum eum illum inventore iure magnam mollitia, quas quasi quia saepe voluptatem? Aperiam distinctio iusto, laborum mollitia nobis perspiciatis quod sint vitae.</span><span>Alias animi blanditiis dolor doloremque ducimus eius fugit, libero magni mollitia necessitatibus nihil nostrum officiis perspiciatis placeat, repellat sit sunt suscipit! Eius impedit iure laborum nesciunt perspiciatis quibusdam quo suscipit.</span><span>A, aut, consectetur culpa cum delectus, dolore dolores doloribus enim facere pariatur quam quasi quibusdam vero. Animi distinctio doloremque ipsa maxime nisi numquam odio officiis, omnis reiciendis repellendus sed soluta!</span><span>Ad commodi consectetur dicta doloribus dolorum eius error esse et eveniet, exercitationem iste obcaecati similique sunt. Autem, culpa cupiditate deserunt, et ipsam molestias nam necessitatibus nostrum, optio quos tempore unde.</span><span>Ad assumenda atque commodi dicta dolor dolorem dolores, ducimus eligendi eum exercitationem, facilis fuga impedit incidunt ipsum laboriosam maxime molestiae necessitatibus nostrum quasi repellat repellendus sunt unde ut voluptates voluptatum!</span><span>Accusamus exercitationem iusto officia repellendus sed? Corporis eligendi fugiat iste nemo pariatur placeat quisquam quod repellat unde vel! Aperiam beatae debitis, distinctio laboriosam laborum natus ullam? Ducimus ipsum molestiae quia!</span><span>Ad blanditiis consequatur debitis eius in incidunt ipsum molestiae similique voluptas. Animi corporis iusto unde. A animi, delectus enim laboriosam libero magni quaerat quasi voluptas? Consequatur explicabo ipsam iste qui!</p>
                </div>
            </div>
            <div class="faq__item">
                <div class="faq__item-header">
                    <h3 class="faq__item-title">Как оплатить тарифный план</h3>
                    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <line class="vertical" y1="10" x2="20" y2="10" stroke="white" stroke-width="2"/>
                        <line class="horizontal" x1="10" y1="20" x2="10" y2="4.37114e-08" stroke="white" stroke-width="2"/>
                    </svg>
                </div>
                <div class="faq__item-content" style="display: none;">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fugit impedit quasi sapiente vero? Cupiditate dolorum error esse minima quod sapiente similique veritatis vitae! Doloremque, quidem veniam? Eum, laborum, maiores.</span><span>Alias aliquid doloribus ducimus eligendi, eos fugiat labore libero obcaecati officiis quod reiciendis repellat! Accusantium doloribus ducimus inventore ipsam nobis odit, omnis pariatur quia ratione, reprehenderit sed similique sunt, veniam.</span><span>Ab alias consequatur dolor dolore enim, eveniet fuga laudantium maxime nemo neque porro quaerat quam qui quidem repellendus sed tempore, ut vitae. Ducimus explicabo itaque iusto labore provident repellendus repudiandae!</span><span>A architecto aspernatur, assumenda atque consectetur, corporis deleniti dolorum eum illum inventore iure magnam mollitia, quas quasi quia saepe voluptatem? Aperiam distinctio iusto, laborum mollitia nobis perspiciatis quod sint vitae.</span><span>Alias animi blanditiis dolor doloremque ducimus eius fugit, libero magni mollitia necessitatibus nihil nostrum officiis perspiciatis placeat, repellat sit sunt suscipit! Eius impedit iure laborum nesciunt perspiciatis quibusdam quo suscipit.</span><span>A, aut, consectetur culpa cum delectus, dolore dolores doloribus enim facere pariatur quam quasi quibusdam vero. Animi distinctio doloremque ipsa maxime nisi numquam odio officiis, omnis reiciendis repellendus sed soluta!</span><span>Ad commodi consectetur dicta doloribus dolorum eius error esse et eveniet, exercitationem iste obcaecati similique sunt. Autem, culpa cupiditate deserunt, et ipsam molestias nam necessitatibus nostrum, optio quos tempore unde.</span><span>Ad assumenda atque commodi dicta dolor dolorem dolores, ducimus eligendi eum exercitationem, facilis fuga impedit incidunt ipsum laboriosam maxime molestiae necessitatibus nostrum quasi repellat repellendus sunt unde ut voluptates voluptatum!</span><span>Accusamus exercitationem iusto officia repellendus sed? Corporis eligendi fugiat iste nemo pariatur placeat quisquam quod repellat unde vel! Aperiam beatae debitis, distinctio laboriosam laborum natus ullam? Ducimus ipsum molestiae quia!</span><span>Ad blanditiis consequatur debitis eius in incidunt ipsum molestiae similique voluptas. Animi corporis iusto unde. A animi, delectus enim laboriosam libero magni quaerat quasi voluptas? Consequatur explicabo ipsam iste qui!</p>
                </div>
            </div>
            <div class="faq__item">
                <div class="faq__item-header">
                    <h3 class="faq__item-title">Как оплатить тарифный план</h3>
                    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <line class="vertical" y1="10" x2="20" y2="10" stroke="white" stroke-width="2"/>
                        <line class="horizontal" x1="10" y1="20" x2="10" y2="4.37114e-08" stroke="white" stroke-width="2"/>
                    </svg>
                </div>
                <div class="faq__item-content" style="display: none;">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fugit impedit quasi sapiente vero? Cupiditate dolorum error esse minima quod sapiente similique veritatis vitae! Doloremque, quidem veniam? Eum, laborum, maiores.</span><span>Alias aliquid doloribus ducimus eligendi, eos fugiat labore libero obcaecati officiis quod reiciendis repellat! Accusantium doloribus ducimus inventore ipsam nobis odit, omnis pariatur quia ratione, reprehenderit sed similique sunt, veniam.</span><span>Ab alias consequatur dolor dolore enim, eveniet fuga laudantium maxime nemo neque porro quaerat quam qui quidem repellendus sed tempore, ut vitae. Ducimus explicabo itaque iusto labore provident repellendus repudiandae!</span><span>A architecto aspernatur, assumenda atque consectetur, corporis deleniti dolorum eum illum inventore iure magnam mollitia, quas quasi quia saepe voluptatem? Aperiam distinctio iusto, laborum mollitia nobis perspiciatis quod sint vitae.</span><span>Alias animi blanditiis dolor doloremque ducimus eius fugit, libero magni mollitia necessitatibus nihil nostrum officiis perspiciatis placeat, repellat sit sunt suscipit! Eius impedit iure laborum nesciunt perspiciatis quibusdam quo suscipit.</span><span>A, aut, consectetur culpa cum delectus, dolore dolores doloribus enim facere pariatur quam quasi quibusdam vero. Animi distinctio doloremque ipsa maxime nisi numquam odio officiis, omnis reiciendis repellendus sed soluta!</span><span>Ad commodi consectetur dicta doloribus dolorum eius error esse et eveniet, exercitationem iste obcaecati similique sunt. Autem, culpa cupiditate deserunt, et ipsam molestias nam necessitatibus nostrum, optio quos tempore unde.</span><span>Ad assumenda atque commodi dicta dolor dolorem dolores, ducimus eligendi eum exercitationem, facilis fuga impedit incidunt ipsum laboriosam maxime molestiae necessitatibus nostrum quasi repellat repellendus sunt unde ut voluptates voluptatum!</span><span>Accusamus exercitationem iusto officia repellendus sed? Corporis eligendi fugiat iste nemo pariatur placeat quisquam quod repellat unde vel! Aperiam beatae debitis, distinctio laboriosam laborum natus ullam? Ducimus ipsum molestiae quia!</span><span>Ad blanditiis consequatur debitis eius in incidunt ipsum molestiae similique voluptas. Animi corporis iusto unde. A animi, delectus enim laboriosam libero magni quaerat quasi voluptas? Consequatur explicabo ipsam iste qui!</p>
                </div>
            </div>
            <div class="faq__item">
                <div class="faq__item-header">
                    <h3 class="faq__item-title">Как оплатить тарифный план</h3>
                    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <line class="vertical" y1="10" x2="20" y2="10" stroke="white" stroke-width="2"/>
                        <line class="horizontal" x1="10" y1="20" x2="10" y2="4.37114e-08" stroke="white" stroke-width="2"/>
                    </svg>
                </div>
                <div class="faq__item-content" style="display: none;">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fugit impedit quasi sapiente vero? Cupiditate dolorum error esse minima quod sapiente similique veritatis vitae! Doloremque, quidem veniam? Eum, laborum, maiores.</span><span>Alias aliquid doloribus ducimus eligendi, eos fugiat labore libero obcaecati officiis quod reiciendis repellat! Accusantium doloribus ducimus inventore ipsam nobis odit, omnis pariatur quia ratione, reprehenderit sed similique sunt, veniam.</span><span>Ab alias consequatur dolor dolore enim, eveniet fuga laudantium maxime nemo neque porro quaerat quam qui quidem repellendus sed tempore, ut vitae. Ducimus explicabo itaque iusto labore provident repellendus repudiandae!</span><span>A architecto aspernatur, assumenda atque consectetur, corporis deleniti dolorum eum illum inventore iure magnam mollitia, quas quasi quia saepe voluptatem? Aperiam distinctio iusto, laborum mollitia nobis perspiciatis quod sint vitae.</span><span>Alias animi blanditiis dolor doloremque ducimus eius fugit, libero magni mollitia necessitatibus nihil nostrum officiis perspiciatis placeat, repellat sit sunt suscipit! Eius impedit iure laborum nesciunt perspiciatis quibusdam quo suscipit.</span><span>A, aut, consectetur culpa cum delectus, dolore dolores doloribus enim facere pariatur quam quasi quibusdam vero. Animi distinctio doloremque ipsa maxime nisi numquam odio officiis, omnis reiciendis repellendus sed soluta!</span><span>Ad commodi consectetur dicta doloribus dolorum eius error esse et eveniet, exercitationem iste obcaecati similique sunt. Autem, culpa cupiditate deserunt, et ipsam molestias nam necessitatibus nostrum, optio quos tempore unde.</span><span>Ad assumenda atque commodi dicta dolor dolorem dolores, ducimus eligendi eum exercitationem, facilis fuga impedit incidunt ipsum laboriosam maxime molestiae necessitatibus nostrum quasi repellat repellendus sunt unde ut voluptates voluptatum!</span><span>Accusamus exercitationem iusto officia repellendus sed? Corporis eligendi fugiat iste nemo pariatur placeat quisquam quod repellat unde vel! Aperiam beatae debitis, distinctio laboriosam laborum natus ullam? Ducimus ipsum molestiae quia!</span><span>Ad blanditiis consequatur debitis eius in incidunt ipsum molestiae similique voluptas. Animi corporis iusto unde. A animi, delectus enim laboriosam libero magni quaerat quasi voluptas? Consequatur explicabo ipsam iste qui!</p>
                </div>
            </div>
            <div class="faq__item">
                <div class="faq__item-header">
                    <h3 class="faq__item-title">Как оплатить тарифный план</h3>
                    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <line class="vertical" y1="10" x2="20" y2="10" stroke="white" stroke-width="2"/>
                        <line class="horizontal" x1="10" y1="20" x2="10" y2="4.37114e-08" stroke="white" stroke-width="2"/>
                    </svg>
                </div>
                <div class="faq__item-content" style="display: none;">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum fugit impedit quasi sapiente vero? Cupiditate dolorum error esse minima quod sapiente similique veritatis vitae! Doloremque, quidem veniam? Eum, laborum, maiores.</span><span>Alias aliquid doloribus ducimus eligendi, eos fugiat labore libero obcaecati officiis quod reiciendis repellat! Accusantium doloribus ducimus inventore ipsam nobis odit, omnis pariatur quia ratione, reprehenderit sed similique sunt, veniam.</span><span>Ab alias consequatur dolor dolore enim, eveniet fuga laudantium maxime nemo neque porro quaerat quam qui quidem repellendus sed tempore, ut vitae. Ducimus explicabo itaque iusto labore provident repellendus repudiandae!</span><span>A architecto aspernatur, assumenda atque consectetur, corporis deleniti dolorum eum illum inventore iure magnam mollitia, quas quasi quia saepe voluptatem? Aperiam distinctio iusto, laborum mollitia nobis perspiciatis quod sint vitae.</span><span>Alias animi blanditiis dolor doloremque ducimus eius fugit, libero magni mollitia necessitatibus nihil nostrum officiis perspiciatis placeat, repellat sit sunt suscipit! Eius impedit iure laborum nesciunt perspiciatis quibusdam quo suscipit.</span><span>A, aut, consectetur culpa cum delectus, dolore dolores doloribus enim facere pariatur quam quasi quibusdam vero. Animi distinctio doloremque ipsa maxime nisi numquam odio officiis, omnis reiciendis repellendus sed soluta!</span><span>Ad commodi consectetur dicta doloribus dolorum eius error esse et eveniet, exercitationem iste obcaecati similique sunt. Autem, culpa cupiditate deserunt, et ipsam molestias nam necessitatibus nostrum, optio quos tempore unde.</span><span>Ad assumenda atque commodi dicta dolor dolorem dolores, ducimus eligendi eum exercitationem, facilis fuga impedit incidunt ipsum laboriosam maxime molestiae necessitatibus nostrum quasi repellat repellendus sunt unde ut voluptates voluptatum!</span><span>Accusamus exercitationem iusto officia repellendus sed? Corporis eligendi fugiat iste nemo pariatur placeat quisquam quod repellat unde vel! Aperiam beatae debitis, distinctio laboriosam laborum natus ullam? Ducimus ipsum molestiae quia!</span><span>Ad blanditiis consequatur debitis eius in incidunt ipsum molestiae similique voluptas. Animi corporis iusto unde. A animi, delectus enim laboriosam libero magni quaerat quasi voluptas? Consequatur explicabo ipsam iste qui!</p>
                </div>
            </div>
        </div>
    </div>
</section>